// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Configure_OneToOne_EFCore.Models;

[Index("AddressOfStudentId", Name = "IX_StudentAddresses_AddressOfStudentId", IsUnique = true)]
public partial class StudentAddress
{
    [Key]
    public int StudentAddressId { get; set; }

    [Required]
    public string Address { get; set; }

    [Required]
    public string City { get; set; }

    [Required]
    public string State { get; set; }

    [Required]
    public string Country { get; set; }

    public int AddressOfStudentId { get; set; }

    [ForeignKey("AddressOfStudentId")]
    [InverseProperty("StudentAddress")]
    public virtual Student AddressOfStudent { get; set; }
}