// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Configure_ManyToMany_EFCore.Models
{
    public partial class Student
    {
        public Student()
        {
            Courses = new HashSet<Course>();
        }

        [Key]
        public int StudentId { get; set; }
        [Required]
        public string Name { get; set; }

        [ForeignKey("StudentId")]
        [InverseProperty("Students")]
        public virtual ICollection<Course> Courses { get; set; }
    }
}